# Site
name: "Mau Luong"
title: "Mau Luong"
description: "Viết lảm nhảm | Coding and Life"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'luongnm'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Mậu Lương
    display_name: Mậu Lương
    gravatar: a0fcf62d3120cf541b39dab1e30fce32
    email: ducluong1905@gmail.com
    web: luongnm.me
    twitter: https://fb.com/luongnm.me
    description: "lười.. lười.. lười..                                                                                                                         "
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
